name: PR Checks
on:
  pull_request:
    branches:
      - "*"
jobs:
  unit-tests:
    name: Unit tests
    uses: lingvano/eas-detox-ci/.github/workflows/unit-tests.yml

  e2e-tests:
    needs: unit-tests
    uses: lingvano/eas-detox-ci/.github/workflows/e2e-tests.yml
    name: E2E tests
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  # eas-update:
  #   needs: e2e-tests
  #   name: Publish preview with EAS update
  #   uses: lingvano/eas-detox-ci/.github/workflows/eas-update.yml
  #   secrets:
  #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
