name: PR Checks
on:
  pull_request:
    branches:
      - "*"
jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Setup repo & install dependencies
        uses: ./.github/actions/setup-repo

      - name: Run Tests
        run: yarn jest --coverage

  run-e2e-tests:
    needs: run-unit-tests
    name: E2E tests
    runs-on: macos-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Setup repo & install dependencies
        uses: ./.github/actions/setup-repo

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🔗 Get current build url
        run: echo "::set-output name=BUILD_URL::$(node cli/getLatestBuildUrl.js)"
        id: url

      - name: 🏗 Download build
        uses: suisei-cn/actions-download-file@v1
        id: downloadedApp
        with:
          url: ${{ steps.url.outputs.BUILD_URL }}
          target: bin/

      - name: 📤 Untar app build
        run: |
          cd bin
          ls -a
          for f in *.tar.gz; do tar -xvf "$f"; done
          ls
          cd ..

      - name: 🏗 Setup Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
          yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: 🧪 Run Detox tests
        run: yarn detox test --configuration ios

  publish-to-expo-go:
    needs: run-e2e-tests
    name: Publish preview to Expo Go
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Setup repo & install dependencies
        uses: ./.github/actions/setup-repo

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # - name: 🚀 Publish preview
      #   run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      # - name: 💬 Comment preview
      #   uses: expo/expo-github-action/preview-comment@v7
      #   with:
      #     channel: pr-${{ github.event.number }}
