name: Setup
on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  setup-repo:
    name: Setup Repo & install dependencies
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 🏗 Setup Yarn
        run: npm install --g yarn

      - name: 📦 Cache dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 📦 Install Node.js dependencies
        run: yarn install --frozen-lockfile --prefer-offline
