name: Unit tests
on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Setup repo & install dependencies
        uses: lingvano/eas-detox-ci/.github/actions/setup-repo@master

      - name: Run Tests
        run: yarn jest --coverage
